apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-platform.fullname" . }}-config
  labels:
    app: config
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: "{{ .Values.config.image.repository }}:{{ .Values.config.image.tag }}"
          imagePullPolicy: {{ .Values.config.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
