apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-platform.fullname" . }}-eventbus
  labels:
    app: eventbus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: eventbus
  template:
    metadata:
      labels:
        app: eventbus
    spec:
      containers:
        - name: eventbus
          image: "{{ .Values.eventbus.image.repository }}:{{ .Values.eventbus.image.tag }}"
          imagePullPolicy: {{ .Values.eventbus.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
