# charts/base-platform/templates/deployment-auth.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-platform.fullname" . }}-auth
  labels:
    app: auth
    {{- include "base-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.auth.replicaCount | default .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: OIDC_ISSUER_URL
              value: {{ .Values.auth.oidc.issuerUrl | quote }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.auth.oidc.clientId | quote }}
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-oidc-secret
                  key: client-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
