apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-platform.fullname" . }}-config
  labels:
    app: config
spec:
  type: ClusterIP
  selector:
    app: config
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
