apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-platform.fullname" . }}-eventbus
  labels:
    app: eventbus
spec:
  type: ClusterIP
  selector:
    app: eventbus
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
