apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-platform.fullname" . }}-ledger-adapter
  labels:
    app: ledger-adapter
spec:
  type: ClusterIP
  selector:
    app: ledger-adapter
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
