apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-platform.fullname" . }}-auth
  labels:
    app: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
