# charts/base-platform/values.yaml  ← (este es el que Argo CD ya está usando)
auth:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/auth
    tag: "latest"
    pullPolicy: Always
  replicaCount: 1

  oidc:
    issuerUrl:   "https://actiora-auth-domain.auth.eu-west-1.amazoncognito.com"
    clientId:    "75nse1j2aunml5eimimni71j"
    redirectUrl: "http://localhost:3000/auth/callback"   # ← aquí pon tu URL local

eventbus:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/eventbus
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

config:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/config
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

normsApi:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/norms-api
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

ledgerAdapter:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/ledger-adapter
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
