auth:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/auth
    tag: "latest"
    pullPolicy: Always
  replicaCount: 1

  oidc:
    issuerUrl:   "https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_CBuUFi3Ly"
    clientId:    "72bgd0a0sapfanm2achlfu0tu4"
    redirectUrl: "http://localhost:3000/auth/callback"


eventbus:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/eventbus
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

config:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/config
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

normsApi:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/norms-api
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

ledgerAdapter:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/ledger-adapter
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
