# charts/base-platform/values.yaml  ← (este es el que Argo CD ya está usando)
auth:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/auth
    tag: "latest"
    pullPolicy: Always
  replicaCount: 1

  oidc:
    issuerUrl:   "https://actiora.auth.eu-west-1.amazoncognito.com"  # dominio Hosted UI configurado
    clientId:    "72bgd0a0sapfanm2achlfu0tu4"                         # nuevo Client ID SPA OAuth
    redirectUrl: "http://localhost:3000/auth/callback"               # URL local de callback

eventbus:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/eventbus
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

config:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/config
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

normsApi:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/norms-api
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

ledgerAdapter:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/ledger-adapter
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
