auth:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/auth
    tag: "latest"
    pullPolicy: Always
  replicaCount: 1

  oidc:
    issuerUrl:   "https://actiora-auth-domain.auth.eu-west-1.amazoncognito.com/oauth2"  # ← /oauth2 al final
    clientId:    "72bgd0a0sapfanm2achlfu0tu4"
    redirectUrl: "http://localhost:3000/auth/callback"

eventbus:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/eventbus
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

config:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/config
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

normsApi:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/norms-api
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

ledgerAdapter:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/ledger-adapter
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
