# charts/base-platform/values.yaml

auth:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/auth
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

  # ← Añadimos la configuración de OIDC
  oidc:
    issuerUrl: "https://<TU_ISSUER_URL>/oauth2/default"   # ← pon aquí tu URL de issuer
    clientId: "actiora-client"                             # ← pon aquí tu client-id
    # El client-secret lo recuperamos del Secret auth-oidc-secret

eventbus:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/eventbus
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

config:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/config
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

normsApi:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/norms-api
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1

ledgerAdapter:
  image:
    repository: 763695378748.dkr.ecr.eu-west-1.amazonaws.com/ledger-adapter
    tag: "latest"
    pullPolicy: IfNotPresent
  replicaCount: 1
