name: CD – ArgoCD Modules

on:
  push:
    paths:
      - 'modules/**'
      - 'charts/modules/**'

jobs:
  sync-modules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [asset-discovery, governance, risk-lab, transparency, conformity, live-compliance]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Log in to ArgoCD
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USER:   ${{ secrets.ARGOCD_USER }}
          ARGOCD_PASS:   ${{ secrets.ARGOCD_PASS }}
        run: |
          argocd login $ARGOCD_SERVER \
            --username $ARGOCD_USER \
            --password $ARGOCD_PASS \
            --insecure

      - name: Sync module ${{ matrix.module }}
        run: argocd app sync ${{ matrix.module }}
