name: CI – Base Platform

on:
  push:
    paths:
      - 'services/auth/**'
      - 'services/eventbus/**'
      - 'services/config/**'
      - 'services/norms-api/**'
      - 'services/ledger-adapter/**'
      - 'libs/**'
      - 'infra/**'
      - 'charts/base-platform/**'
      - 'Makefile'
      - 'docker-compose.yml'
  pull_request:
    paths:
      - 'services/auth/**'
      - 'services/eventbus/**'
      - 'services/config/**'
      - 'services/norms-api/**'
      - 'services/ledger-adapter/**'
      - 'libs/**'
      - 'infra/**'
      - 'charts/base-platform/**'
      - 'Makefile'
      - 'docker-compose.yml'

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        svc: [auth, eventbus, config, norms-api, ledger-adapter]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Cache Go modules for ${{ matrix.svc }}
        uses: actions/cache@v3
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.svc }}-${{ hashFiles('services/${{ matrix.svc }}/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Lint & Test ${{ matrix.svc }}
        working-directory: services/${{ matrix.svc }}
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run ./...
          go test ./... -v -coverprofile=coverage.out

      - name: Build Docker image ${{ matrix.svc }}
        working-directory: services/${{ matrix.svc }}
        run: docker build -t ghcr.io/tu-org/actiora/${{ matrix.svc }}:latest .
      
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.svc }}-coverage
          path: services/${{ matrix.svc }}/coverage.out
